[build-system]
build-backend = 'mesonpy'
requires = ['meson-python',
            'numpy>=2.0.0']


[project]
name = 'PyGeTe'
dynamic = ["version"]
dependencies = [
	     "numpy<2.0.0",
	     "ASE",
]
